baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://nkmakes.github.io" # the base hostname & protocol for your site, e.g. http://example.com
title: nkmakes | Niko's projects personal blog - DIY - IOT - 3dprint
logo: logo.svg # You can add own logo.
description: Niko's projects personal blog - DIY | IOT | 3dprint


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-seo-tag

paginate: 5
paginate_path: "/page/:num"


# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Colections
collections:
  projects:
    output: true



# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed